### ISSUE TITLE
Use LDAPJS instead of node-ldapauth

### ISSUE THREAD

**Issue by jsloyer** [bnoguchi/everyauth#335]
Since node-ldapauth requires binary modules there is a full javascript version of an ldap client and server, LDAPJS, is there a way to use that instead of node-ldapauth for ldap authentication?

**Comment by aaroncalderon** [comment]
It is possible to solve this issue by using `ldapauth-fork`. l`dapauth` and `ldapauth-fork` use ldapjs internally, however, it is the package `bcryptjs` that is broken (or rather old).
